kind: ConfigMap
apiVersion: v1
metadata:
  name: object-detection-ml-backend-config
  labels:
    dependency.staroid.com/export: labelstudio-ml-backend-config
data:
  ML_BACKEND_URL: "http://object-detection.{{.Namespace}}:9090"
